import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BottomMenu } from "@/widgets/bottom-menu";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["cyrillic", "latin"]
})

export const metadata: Metadata = {
  title: "Green Dark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased px-[30px] py-10 h-screen`}
      >
        {children}
        <BottomMenu />
      </body>
    </html>
  );
}
